### ISSUE TITLE
UserAgent string for Microsoft Edge on Mac OS is 'Edg' not 'Edge'

### ISSUE THREAD

**Issue by synthphonic** [DannyBoyNg/UserAgentService#1]
Hello, first of all, your little help is very helpful! Thanks for that! 

Secondly, I found out that the user agent for Microsoft Edge on MacOS X is "Edg" instead of "Edge".

below is the full string:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36 Edg/89.0.774.48`

Thanks!

**Comment by DannyBoyNg** [comment]
I updated the package to properly detect the Edge browser. Version 1.0.3 is now available for you to download.
