### ISSUE TITLE
Consider exposing the internal dictionaries

### ISSUE THREAD

**Issue by nathan-alden-sr** [DannyBoyNg/UserAgentService#2]
Your code exposes the mapping dictionaries as `internal`, which means that developers have no way of adding to or otherwise modifying the list. That puts a dependency on you to maintain all the mappings basically forever. Please consider exposing the dictionaries as configuration, probably on the `UserAgentSettings` class.

Something like this should be possible (with `Platforms`) being pre-initialized to the current dictionaries you already define.
```cs
userAgentSettings.Platforms.Add("windows nt 11.0", "Windows 11");
```

**Comment by DannyBoyNg** [comment]
I merged your pull request, after some testing I found out that the platforms were not matching anymore, so I had to revert one of your commits. 

The mapping dictionaries will stay public.

**Comment by randyburden** [comment]
FYI, this change was never published to NuGet so for the time being we pulled the source code directly into our project.

**Comment by DannyBoyNg** [comment]
Nuget package has been published.
